### ISSUE TITLE
Can´t scroll if you have a long list of updates.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [wwboyer/RPCS3-Game-Update-Downloader#1]
![](https://user-images.githubusercontent.com/13170204/86591951-cafe1100-bf92-11ea-8efb-264be150a509.png)

As you can see, This can be a bit problematic, when you have a monitor more wide than high. 

I suppose I can easily just relaunch the script when those are done, and it will show the next one that I couldn’t access, but a little scrollable list would be nice just to fix that minor issue.

**Comment by wwboyer** [comment]
Hey @PoorPocketsMcNewHold,

I'm sorry that it took so long for me to see this. I must've somehow missed an email and, to be perfectly honest, I'm surprised that another person actually used my program. I just pushed some code that should make the list scrollable. It's not very pretty but it should work fine. Let me know if it works on your machine.
